services:
  front:
    container_name: front
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "5173:5173"
    volumes:
      - "./app/src:/app/src"
      - "./app/public:/app/public"
    environment:
      - VITE_API_URL=http://localhost:3000
    networks:
      - linkedin

  back:
    container_name: back
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "3000:3000"
    volumes:
      - "./api/src:/api/src"
      - "./api/libs:/api/libs"
    env_file:
      - "./.env"
    networks:
      - linkedin

networks:
  linkedin: {}
  